name: CI
on:
  pull_request:
  push:
    branches: [master]

permissions: {}

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup environment
        uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2.0.2
        with:
          version: ^11.0.0
          runtime: node@lts
          cache: true

      - name: Build
        run: pnpm build

      - name: Check formatting
        run: pnpm format:check

      - name: Lint
        run: pnpm lint

      - name: Check types
        run: |
          pnpm typecheck
          pnpm attw

      - name: Test
        run: pnpm rstest --coverage --coverage.reportOnFailure

      - name: Upload coverage
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: coverage
          path: coverage
