name: Release
on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      # - name: Load secrets from 1Password
      #   uses: 1Password/load-secrets-action@v5

      - name: Setup
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        with:
          version: ^11.0.0
          runtime: node@lts
          cache: false

      - name: Build
        run: pnpm build

      - name: Publish
        run: pnpm publish --no-git-checks
